/* tslint:disable:max-line-length */

import { Tixin, Type } from '@tdm/tixin';
import { BaseActiveRecord, externalMetadataStore } from '@tdm/core';
import { HttpAdapter } from './core';

import { BaseRestResource, BaseRestResourceStatic  } from './base-http-resource';


/* GENERATED BY scripts/generic_codegen.js */
export function RestMixin<Model, TypeofModel>(): Type<Model & BaseActiveRecord<Model> & BaseRestResource> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel;
export function RestMixin<Model, TypeofModel>(model: TypeofModel & Type<Model>): Type<Model & BaseActiveRecord<Model> & BaseRestResource> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel;
export function RestMixin<Model, TypeofModel, T1, C1>(model: TypeofModel & Type<Model>, m1: C1 & Type<T1>): Type<Model & BaseRestResource & T1> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel & C1;
export function RestMixin<Model, TypeofModel, T1, C1, T2, C2>(model: TypeofModel & Type<Model>, m1: C1 & Type<T1>, m2: C2 & Type<T2>): Type<Model & BaseActiveRecord<Model> & BaseRestResource & T1 & T2> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel & C1 & C2;
export function RestMixin<Model, TypeofModel, T1, C1, T2, C2, T3, C3>(model: TypeofModel & Type<Model>, m1: C1 & Type<T1>, m2: C2 & Type<T2>, m3: C3 & Type<T3>): Type<Model & BaseActiveRecord<Model> & BaseRestResource & T1 & T2 & T3> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel & C1 & C2 & C3;
export function RestMixin<Model, TypeofModel, T1, C1, T2, C2, T3, C3, T4, C4>(model: TypeofModel & Type<Model>, m1: C1 & Type<T1>, m2: C2 & Type<T2>, m3: C3 & Type<T3>, m4: C4 & Type<T4>): Type<Model & BaseActiveRecord<Model> & BaseRestResource & T1 & T2 & T3 & T4> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel & C1 & C2 & C3 & C4;
export function RestMixin<Model, TypeofModel, T1, C1, T2, C2, T3, C3, T4, C4, T5, C5>(model: TypeofModel & Type<Model>, m1: C1 & Type<T1>, m2: C2 & Type<T2>, m3: C3 & Type<T3>, m4: C4 & Type<T4>, m5: C5 & Type<T5>): Type<Model & BaseActiveRecord<Model> & BaseRestResource & T1 & T2 & T3 & T4 & T5> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel & C1 & C2 & C3 & C4 & C5;
export function RestMixin<Model, TypeofModel, T1, C1, T2, C2, T3, C3, T4, C4, T5, C5, T6, C6>(model: TypeofModel & Type<Model>, m1: C1 & Type<T1>, m2: C2 & Type<T2>, m3: C3 & Type<T3>, m4: C4 & Type<T4>, m5: C5 & Type<T5>, m6: C6 & Type<T6>): Type<Model & BaseActiveRecord<Model> & BaseRestResource & T1 & T2 & T3 & T4 & T5 & T6> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel & C1 & C2 & C3 & C4 & C5 & C6;
export function RestMixin<Model, TypeofModel, T1, C1, T2, C2, T3, C3, T4, C4, T5, C5, T6, C6, T7, C7>(model: TypeofModel & Type<Model>, m1: C1 & Type<T1>, m2: C2 & Type<T2>, m3: C3 & Type<T3>, m4: C4 & Type<T4>, m5: C5 & Type<T5>, m6: C6 & Type<T6>, m7: C7 & Type<T7>): Type<Model & BaseActiveRecord<Model> & BaseRestResource & T1 & T2 & T3 & T4 & T5 & T6 & T7> & typeof BaseRestResource & BaseRestResourceStatic<Model> & TypeofModel & C1 & C2 & C3 & C4 & C5 & C6 & C7;


export function RestMixin<Model, TypeofModel, TMIXIN, CMIXIN>(model?: TypeofModel & Type<Model>, ...mixins: Array<CMIXIN & Type<TMIXIN>>): Type<Model & BaseActiveRecord<Model> & BaseRestResource & TMIXIN> & typeof BaseRestResource & BaseRestResourceStatic<Model> & CMIXIN & TypeofModel {
  model = model || <any>class {};

  /**
   * Marking the mixin BaseRestResource for model.
   * Since model is an extending class, it's type will be traversed and looked up for mixins
   * so the deriving class (base) will get all the actions from the BaseRestResource
   *
   */
  externalMetadataStore.markMixins(model, HttpAdapter, BaseRestResource, ...mixins);

  const result = Tixin(model, BaseRestResource);

  externalMetadataStore.buildIfReady(result, HttpAdapter);

  return result as any;
}
export type RestMixin<Model> = Model & BaseActiveRecord<Model> & BaseRestResource;

/* tslint:disable:max-line-length */
